extends: airbnb-base
plugins:
  - import
  - es-beautifier
rules:
  comma-dangle: 0
  consistent-return: 1
  no-func-assign: 1
  no-param-reassign: 1
  no-return-assign: 1
  no-shadow: 1
  no-underscore-dangle: 0
  no-use-before-define: 1
  prefer-promise-reject-errors: 1
  semi: 0
  no-restricted-properties: 0
